[package]
name = "rust_chip8"
version = "0.1.0"
authors = ["Juan Antonio <JuantAldea@users.noreply.github.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
rand = "*"
log = "*"
sdl2 = "*"
env_logger ="*"
spin_sleep = "0.3.7"
